name: Release And Publish on muanual trigger

on:
  workflow_dispatch

jobs:
  build_tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: -1

      - name: XXX
        run: |
          echo ${{ github.repository }}
          echo ${{ github.repository_id }}
          echo ${{ github.repository_owner }}
          git log
